# Generated by Django 5.2.15 on 2026-06-22 11:29

import apps.homework.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        validators=[apps.homework.models.validate_course_slug],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "scoring_method",
                    models.CharField(
                        choices=[
                            ("best", "Best attempt"),
                            ("recent", "Most recent submission"),
                            ("superscore", "Superscored"),
                        ],
                        default="best",
                        help_text="How each student's score on a problem is derived from their submissions.",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="course_thumbnails/"),
                ),
                ("thumbnail_preset", models.CharField(blank=True, max_length=120)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive courses are filed under “Previous courses” for students.",
                    ),
                ),
                ("grade_a_min", models.PositiveSmallIntegerField(default=90)),
                ("grade_b_min", models.PositiveSmallIntegerField(default=80)),
                ("grade_c_min", models.PositiveSmallIntegerField(default=70)),
                ("grade_d_min", models.PositiveSmallIntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses_instructing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses_enrolled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses_assisting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeanSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lean_source_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        validators=[apps.homework.models.validate_assignment_slug],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="homework.course",
                    ),
                ),
                (
                    "source_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assignments",
                        to="homework.leansourcefile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("course", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional display name shown to students; defaults to its position, e.g. Problem 3.",
                        max_length=255,
                    ),
                ),
                ("statement", models.TextField(blank=True)),
                (
                    "required_code",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A code snippet that must remain in student submissions.",
                    ),
                ),
                (
                    "grading_stub",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional Lean code appended to submissions for grading.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1, help_text="Points awarded for solving this problem"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="homework.assignment",
                    ),
                ),
                (
                    "visible_source_files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Imported source files students can view on this problem. Others stay hidden but are still compiled into submissions.",
                        related_name="visible_in_problems",
                        to="homework.leansourcefile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("result", models.TextField(blank=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="homework.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("fixed_code", "Fixed Code"),
                            ("editable_code", "Editable Code"),
                        ],
                        default="editable_code",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="homework.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("problem", "order")},
            },
        ),
    ]
