# Generated by Django 5.2.15 on 2026-06-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="allowed_axioms",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated extra axioms the proof may depend on, beyond Lean's standard sound ones (propext, Classical.choice, Quot.sound) — e.g. axioms this problem provides.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="allowed_constructs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Disallowed Lean constructs (sorry, axiom, IO, #eval, …) to re-permit for this problem. Empty = enforce the full blacklist.",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="axiom_target",
            field=models.CharField(
                blank=True,
                help_text="Declaration to audit with `#print axioms` after a successful compile (e.g. the theorem the student proves). Blank = skip the axiom check.",
                max_length=200,
            ),
        ),
    ]
