# Generated by Django 5.2.15 on 2026-06-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0002_problem_allowed_axioms_problem_allowed_constructs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="renewed_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewals",
                to="homework.course",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="section",
            field=models.CharField(
                blank=True, help_text="e.g. “Section 002”.", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="term",
            field=models.CharField(
                blank=True, help_text="e.g. “Summer 2026”.", max_length=60
            ),
        ),
    ]
