# Generated by Django 5.2.16 on 2026-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0003_course_renewed_from_course_section_course_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="allowed_axioms",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated extra axioms the proof may depend on, beyond Lean's standard sound ones (propext, Classical.choice, Quot.sound): e.g. axioms this problem provides.",
                max_length=500,
            ),
        ),
    ]
